/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngineManager;
import javax.script.ScriptEngine;
import javax.script.ScriptException;
/**
 *
 * @author GabrielNN
 */
public class calculadora extends javax.swing.JFrame {
    String textoCalc = "0";
    boolean calculo = false;
    boolean calculo1 = true;
    boolean ponto = true;
    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        jTextField1.setText(textoCalc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new java.awt.GridLayout(5, 4, 1, 1));

        jToggleButton6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton6.setText("←");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton6);

        jToggleButton7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton7.setText("CE");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton7);

        jToggleButton16.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton16.setText("C");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton16);

        jToggleButton3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton3.setText("±");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton3);

        jToggleButton13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton13.setText("7");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton13);

        jToggleButton11.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton11.setText("8");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton11);

        jToggleButton14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton14.setText("9");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton14);

        jToggleButton5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton5.setText("+");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton5);

        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton1.setText("4");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1);

        jToggleButton2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton2.setText("5");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton2);

        jToggleButton15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton15.setText("6");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton15);

        jToggleButton4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton4.setText("-");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton4);

        jToggleButton8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton8.setText("1");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton8);

        jToggleButton9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton9.setText("2");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton9);

        jToggleButton10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton10.setSelected(true);
        jToggleButton10.setText("3");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton10);

        jToggleButton12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton12.setText("*");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton12);

        jToggleButton17.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton17.setText("0");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton17);

        jToggleButton18.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton18.setText(".");
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton18);

        jToggleButton19.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton19.setText("=");
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton19);

        jToggleButton20.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jToggleButton20.setText("/");
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void teclarNumero(String numero){
    if(textoCalc.length() == 1 && textoCalc == "0"){
        textoCalc = "";                
    }    
    textoCalc += numero;
        calculo = true;
        calculo1 = true;
        jTextField1.setText(textoCalc);
    }
    
    private void apagarBackSpace(){
        if(textoCalc.endsWith(".") == true){
            ponto = true;
        }
        if(textoCalc.startsWith("(") && textoCalc.endsWith(")")){
            textoCalc = textoCalc.substring(1,textoCalc.length());
        }
        textoCalc = textoCalc.substring(0,textoCalc.length()-1);     
        if(textoCalc.length() == 0){
            textoCalc = "0";
            ponto = true;
        }
        
        if(textoCalc.endsWith("+")||textoCalc.endsWith("-")||textoCalc.endsWith("/")||textoCalc.endsWith("*")){
            calculo = false;
            calculo1 = false;          
            
        }else{            
            calculo = true;
            calculo1 = true;
        }
        if(textoCalc.length() == 1 && textoCalc == "0"){
            ponto = true;
        }
        
        jTextField1.setText(textoCalc);
    }
    
    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        teclarNumero("9");
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        teclarNumero("7");
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
    apagarBackSpace();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        teclarNumero("1");
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        teclarNumero("2");
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        teclarNumero("3");
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        teclarNumero("4");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        teclarNumero("5");
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        teclarNumero("6");
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        teclarNumero("8");
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        teclarNumero("0");
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        if(ponto == true){
            if(textoCalc.endsWith("*")||textoCalc.endsWith("-")||textoCalc.endsWith("+")||textoCalc.endsWith("/")){
                textoCalc += "0.";
                ponto = false;
                jTextField1.setText(textoCalc);
            }else{
                textoCalc += ".";
                ponto = false;
                jTextField1.setText(textoCalc);
            }
        } 
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        if(calculo == true && calculo1 == true){
        textoCalc += "+";
        jTextField1.setText(textoCalc);
        calculo = false;        
        ponto = true;
        }        
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        if(textoCalc.length()==1 && textoCalc == "0"){
            textoCalc = "";
        }
        if(calculo1 == true){
        textoCalc += "-";
        jTextField1.setText(textoCalc);
        calculo = false;
        calculo1 = false;
        ponto = true;
        }        
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        if(calculo == true && calculo1 == true){
        textoCalc += "*";
        jTextField1.setText(textoCalc);
        calculo = false;        
        ponto = true;
        }        
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        if(calculo == true && calculo1 == true){
        textoCalc += "/";
        jTextField1.setText(textoCalc);
        calculo = false;        
        ponto = true;
        }        
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
    ScriptEngineManager mgr = new ScriptEngineManager();
    ScriptEngine engine = mgr.getEngineByName("JavaScript");    
    
    if(textoCalc.endsWith("+")||textoCalc.endsWith("-")||textoCalc.endsWith("/")||textoCalc.endsWith("*")){
        apagarBackSpace();
        calculo = true;
        calculo1 = true;
    }
    
    if(textoCalc.endsWith(".")){
        apagarBackSpace();
        ponto = true;
    }    
    String contaString = textoCalc;    
    try {
        String text = engine.eval(contaString).toString();
        textoCalc = text;            
    }catch (ScriptException ex) {               
            Logger.getLogger(calculadora.class.getName()).log(Level.SEVERE, null, ex);
    }
    //if(textoCalc.endsWith(".0")){
        //apagarBackSpace();
        //apagarBackSpace();
    //}
    jTextField1.setText(textoCalc);              
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        textoCalc = "0";
        jTextField1.setText(textoCalc);        
        calculo = false;
        calculo1 = true;
        ponto = true;
        
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if(textoCalc.length() == 1 && textoCalc == "0"){}else{
            textoCalc = "("+textoCalc+")*-1";
            jTextField1.setText(textoCalc);
        
            if(textoCalc.endsWith("+")||textoCalc.endsWith("-")||textoCalc.endsWith("/")||textoCalc.endsWith("*")){
                calculo = false;
                calculo1 = false;
            }else{            
                calculo = true;
                calculo1 = true;
            }
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        boolean teste = true;
        
        if(textoCalc.contains("+")||textoCalc.contains("-")||textoCalc.contains("/")||textoCalc.contains("*")){        
            if(textoCalc.endsWith("+")||textoCalc.endsWith("-")||textoCalc.endsWith("/")||textoCalc.endsWith("*")){
                apagarBackSpace();                
            }
            while(teste == true && textoCalc.length() > 0){
                if(textoCalc.endsWith(".") == true){
                    ponto = true;
                }
                if(textoCalc.endsWith("+")||textoCalc.endsWith("-")||textoCalc.endsWith("/")||textoCalc.endsWith("*")){
                    apagarBackSpace();
                    teste = false;
                    if(textoCalc.endsWith("+")||textoCalc.endsWith("-")||textoCalc.endsWith("/")||textoCalc.endsWith("*")){
                        apagarBackSpace();
                        if(textoCalc.startsWith("(") && textoCalc.endsWith(")")){
                            //textoCalc = textoCalc.substring(1,textoCalc.length()-1);
                            apagarBackSpace();
                        }
                    }
                }else{
                    apagarBackSpace();
                }
            }
        }else{        
            textoCalc = "0";
            ponto = true;
        }
        
        if(textoCalc.length() == 0){
            textoCalc = "0";
            ponto = true;
        }
        if(textoCalc.endsWith("+")||textoCalc.endsWith("-")||textoCalc.endsWith("/")||textoCalc.endsWith("*")){
            calculo = false;
            calculo1 = false;
        }else{            
            calculo = true;
            calculo1 = true;
        }
        
        jTextField1.setText(textoCalc);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
